config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'workouts/new'

  devise_for :users, :controllers => { registrations: "users/registrations" }

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/signup" => "devise/registrations#new"
  end
  resources :user do
    resources :body_metrics
  end

  resources :user do
    resources :food_records
  end

  resources :food_items
  resources :workouts

end

app/models/food_record.rb
class FoodRecord < ActiveRecord::Base
  belongs_to :user, dependent: :destroy

  validates :item, presence: true
  validates :intake_date, presence: true
  validates :quantity, presence: true

  after_create :compute_calories
  after_update :update_calories

  def compute_calories
    @food_record = User.find_by(id: user_id).food_records.last
    #if @food_record.calculated_calories.nil?
    @item = FoodItem.find_by(item: @food_record.item)
    @calories_intake = @item.calories*@food_record.quantity
    @food_record.update_attributes!(calculated_calories: @calories_intake)
  end

  def update_calories
    @food_record = User.find_by(id: user_id).food_records.find_by(id: id)
    @item = FoodItem.find_by(item: @food_record.item)
    @calories_intake = @item.calories*@food_record.quantity
    if @food_record.calculated_calories != @calories_intake
      @food_record.update_attributes!(calculated_calories: @calories_intake)
    end
  end
end

app/controllers/food_records_controller.rb
class FoodRecordsController < ApplicationController
  def new
    @user_food_record = FoodRecord.new
    @food_list = FoodItem.all
  end

  def create
    @user_food_record = current_user.food_records.create(food_record_params)
    if @user_food_record.save
      redirect_to  user_food_record_path(current_user.id,@user_food_record.id)
    else
      render 'new'
    end
  end

  def show
    @food_record = current_user.food_records.last
    @food_list = current_user.food_records.where(intake_date: Date.today)
  end

  def edit
    @user_food_record_edit = FoodRecord.find_by(id: params[:id])
  end

  def update
    @user_food_record_edit = FoodRecord.find_by(id: params[:id])
    @user_food_record_edit.update_attributes(food_record_params)
    redirect_to  user_food_record_path(current_user.id,@user_food_record_edit.id)
  end

  private

  def food_record_params
    params.require(:food_record).permit(:item, :quantity, :intake_date, :calculated_calories)
  end
end

app/helpers/food_records_helper.rb
module FoodRecordsHelper
end

app/views/food_records/edit.html.haml
= form_for([current_user, @user_food_record_edit],:class => "form-horizontal") do |f|
  = render 'shared/error_messages', object: f.object
  = f.label :item, class: 'control-label'
  = f.select("item",FoodItem.all.collect {|a| a.item },prompt: "Select item")
  %br/
  = f.label :quantity, class: 'control-label'
  = f.number_field :quantity
  %br/
  = f.label :intake_date, class: 'control-label'
  = f.date_field :intake_date
  %br/
  = f.submit "compute calories"

app/views/food_records/new.html.haml
= form_for([current_user, @user_food_record],:class => "form-horizontal") do |f|
  = render 'shared/error_messages', object: f.object
  = f.label :item, class: 'control-label'
  = f.select("item",FoodItem.all.collect {|a| a.item },prompt: "Select item")
  %br/
  = f.label :quantity, class: 'control-label'
  = f.number_field :quantity
  %br/
  = f.label :intake_date, class: 'control-label'
  = f.date_field :intake_date
  %br/
  = f.submit "compute calories"

app/views/food_records/show.html.haml
%p You gained #{@food_record.calculated_calories} calories by consuming #{@food_record.item}
%h3 Todays Food Record
%table.table{:border => "1"}
  %tr
    %th Item
    %th Quantity
    %th Calories
    %th Edit
  - @food_list.each do |food_record|
    %tr
      %td= food_record.item
      %td= food_record.quantity
      %td= food_record.calculated_calories
      %td= link_to 'edit', edit_user_food_record_path(current_user.id,food_record.id)