config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'workouts/new'

  devise_for :users, :controllers => { registrations: "users/registrations" }

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/signup" => "devise/registrations#new"
  end
  resources :user do
    resources :body_metrics
  end

  resources :user do
    resources :food_records
  end

  resources :food_items
  resources :workouts

end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    © All rights reserved
  %nav
    %ul
      %li= link_to "Help",'#'
      %li= link_to "Privacy",'#'

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-fixed-top.navbar-inverse
    .header_container
      = link_to "Calories", root_path, id: "logo"
      %nav
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to "Home",   root_path
            - if user_signed_in?
              %ul
                = link_to   edit_user_body_metric_path(current_user.id,current_user.body_metric.id) do
                  %li TDEE calculator
                = link_to food_items_path do
                  %li Food List
                - if current_user.admin?
                  = link_to new_workout_path do
                    %li Workout Videos
                - else
                  = link_to  workouts_path do
                    %li Workout Videos
                = link_to new_user_food_record_path(current_user.id) do
                  %li Food Record
          - if user_signed_in?
            %li
              = link_to "Sign out", destroy_user_session_path, :method => :delete
          - else
            %li= link_to "Login", login_path
          %li= link_to "About", '#'
          %li= link_to "Contact Us",'#'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CaloriesApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        %div{:class => "alert alert-#{message_type}"}= message
      .align_center
        = yield
      = render 'layouts/footer'